FROM ubuntu:latest
LABEL maintainer "PyContribs <pycontribs@googlegroups.com>"

RUN \
    apt-get update -y && \
    apt-get install -y apt-utils gcc python3 python3-dev libssl-dev

ENV SHELL /bin/bash
